### ISSUE TITLE
MT icon - connection indicator

### ISSUE THREAD

**Issue by Tahkis** [meshtastic/ATAK-Plugin#1]
MT icon has only two states at the moment, red and green.

The icon shows green even if the MT app has no connection to LORA radio.

The icon should show red when there is no radio connection available. In addition there could be another color/indicator showing connection to MT app exist but no radio connection available.

**Comment by niccellular** [comment]
The connection green indicates connected to the IMeshService. The intent of this plugin is to be simple not a kitchen sink. The plugin is not responsible for talking to the LORA hardware, its sole existence is to talk to the IMeshService.
