### ISSUE TITLE
Option to work with non-ATAK nodes

### ISSUE THREAD

**Issue by lyrics1988123** [meshtastic/ATAK-Plugin#14]
Im not sure if this is possible, but if it is i would categorize this as a feature request:

I dont have the real usecase for ATAK (a team which could benefit from ATAK) but i love the idea of ATAK (plugin support, toolkit, etc.).
So i was trying to use ATAK as a swiss army knife app including meshtastic. I wanted to be able to see other nodes and work with them the same way like in meshtastic (see them, write them, ping them something on the map) while still enjoy other interesting features of atak for myself (knowing that drawing would not transmit to others, etc). 

As far as i understand this is not possible at the moment. I tried it and i saw all nodes of my mesh network in ATAK for a few seconds but then they were gone forever (none of them is using ATAK). Reinstalling didnt change anything.

Is it posssible to do that, so i can use ATAK as a type of alternative app to meshtastic android?

**Comment by niccellular** [comment]
1.0.8 now has a toggle that allows bare meshtastic devices to appear in ATAK without having a paired EUD.
