### ISSUE TITLE
Environment Metrics - report data without attached sensors

### ISSUE THREAD

**Issue by daskalovst** [meshtastic/ATAK-Plugin#17]
In the remarks section, there are Environment Metrics even if the node doesn't have an attached sensor. For instance, it might show "temperature 1.4E-45," which clearly indicates the measurement is 0, and "humidity 1.9612345E23," indicating a measurement outside the theoretically possible range.

Here are some proposals for improvement:

Include only available data dynamically in the remarks field.
Round the values to appropriate tolerances based on datasheets of the sensors attached.

**Comment by niccellular** [comment]
PR's welcome.
