### ISSUE TITLE
TAK_Packet payload decoding error

### ISSUE THREAD

**Issue by niccellular** [meshtastic/ATAK-Plugin#19]
There's some junk getting passed in the protobufs which makes it fail to decode.

**Comment by niccellular** [comment]
getIsCompressed() is not returning the correct value

**Comment by DB-SOC** [comment]
Is this potentially connected to the constant retransmission/excessive channel utilization issue that I just posted?

**Comment by niccellular** [comment]
no, its just the firmware sending us a compressed tak_packet and the plugin not knowing how to handle it. it shouldn't cause any problems, just noise in the logs
