### ISSUE TITLE
Use in ATAK?

### ISSUE THREAD

**Issue by brandonpsmith** [meshtastic/ATAK-Plugin#2]
I've read [this](https://meshtastic.org/docs/software/integrations/integrations-atak-plugin) page and it gives a brief overview of how the plugin integrates with ATAK. I see a green meshtastic icon in the lower left hand corner of the ATAK map, which means it's bound to the IMeshService. But I can't find any more information on how to use this plugin or what functionality I now have in ATAK?

**Comment by niccellular** [comment]
All your outgoing CoT will be sent over the meshtastic link in addition to whatever other networks you have established
