### ISSUE TITLE
[Bug] Multiple node entries in ATAK's Contacts (TAK Tracker)

### ISSUE THREAD

**Issue by habr05** [meshtastic/ATAK-Plugin#25]
When a node is configured as TAK Tracker and no ATAK client is using, it shows in ATAK's Contacts with Meshtastic's _Long Name_. However, when ATAK client connects to it, ATAK's Contacts displays it as two entries -> Meshtastic's _Long Name_ and connected ATAK's _Callsign_. 

The expected behavior would be to update _Long Name_ in Contacts with a _Callsign_. and reverse it when ATAK stops using the node.

**Comment by niccellular** [comment]
no its working as programmed
