### ISSUE TITLE
TAK Role 

### ISSUE THREAD

**Issue by Lumpi81** [meshtastic/ATAK-Plugin#28]
Hello, 
First of all, thank you for this project and your work on it. 

Maybe I have a problem understanding...
I selected the TAK role for my device in the mobile app. After that, the app no ​​longer shows my own location. 
If I change the role back to “Client” it is there. I see my own location in the app like in ATAK. 
Is there a reason for this or is it a bug?
Meshtastic Firmware 2.3.13.83f5ba0 Beta and ATAK-Plugin-Meshtastic.Plugin-1.0.25-b4cd4f08-4.10.0-civ-release.apk
Thanks for your answer.

I would also like to ask whether it is planned to use the ATAK plugin to manual query the position of individual or all clients in the network in the future. Or does that already exist?
If I do this using the Meshtastic app, it automatically updates this in the ATAK app. However, switching between the apps is impractical from my point of view. Thank you

**Comment by niccellular** [comment]
TAK role basically sets all Meshtastic intervals for stuff to infinity. When you use TAK role you are not caring about Meshtastic at all, its meant to be used only in ATAK.

ATAK has no concept of manually querying the position over meshtastic.
