### ISSUE TITLE
Atak-Plugin Crashing Android 8

### ISSUE THREAD

**Issue by grooldude488** [meshtastic/ATAK-Plugin#33]
Having an issue with Meshtastic Atak plug-in crashing the Atak app once everything is loaded; otherwise everything works as it should. 

LG V20 works amazing for a day or two on a fresh factory reset and atak/plugin install, then it starts crashing for the reasons i assume are explained in the crash log file below. With the plugin disabled it does not crash.

Using newest full version of Atak from .gov website, and newest plugin.

[ATAKNativeCrash-28393[1].txt](https://github.com/user-attachments/files/16859645/ATAKNativeCrash-28393.1.txt)

**Comment by niccellular** [comment]
Not maintaining support for Android 8
