### ISSUE TITLE
RQ: Meshtastic Device Battery level

### ISSUE THREAD

**Issue by daskalovst** [meshtastic/ATAK-Plugin#6]
Hello, 
Just idea for the next versions.

It will be great if we can observe remaining battery level on the meshtastic device directly from the TAK screen

Depend on the position reporting settings in ATAK,  is happen that the battery of the meshtastic device is depleted quiet fast.

**Comment by daskalovst** [comment]
We need to address the bug regarding the green icon in ATAK when the Meshtastic hardware isn't connected. Currently, the green indication shows up in ATAK as long as the plugin communicates with the Meshtastic app, regardless of whether the Meshtastic app is connected to a device or not. This situation can be misleading: the battery might be draining, indicating offline status, yet everything appears normal with a green icon, but you're actually completely disconnected

**Comment by niccellular** [comment]
I just this on a Tbeam that the icon goes red when I turn the Tbeam off.

**Comment by niccellular** [comment]
version 1.0.8 now writes the NodeInfo into the remarks section, you should be able to observe the battery level there.
